version: '3'

services:

  generator:
   image: spirogov/kafka-fraud-generator
   environment:
     KAFKA_BROKER_URL: broker:9093
     TRANSACTIONS_TOPIC: queuing.transactions
     TRANSACTIONS_PER_MINUTE: 4

  detector:
    image: spirogov/kafka-fraud-detector
    environment:
      KAFKA_BROKER_URL: broker:9093
      TRANSACTIONS_TOPIC: queuing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud

  agent:
    image: spirogov/kafka-fraud-agent
    depends_on:
      - db
    environment:
      KAFKA_BROKER_URL: broker:9093
      TOPIC: streaming.transactions.fraud
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db:5432
      DB_NAME: deals
    restart: always

  api:
    image: spirogov/kafka-fraud-api
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db:5432
      DB_NAME: deals
    restart: always
    ports:
      - 5000:5000

  db:
    image: postgres
    environment:
      POSTGRES_DB: deals
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432

networks:
  default:
    external:
      name: kafka-network
